/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuthedRouteImport } from './routes/admin/_authed'
import { Route as AdminAuthedSettingsRouteImport } from './routes/admin/_authed/settings'
import { Route as AdminAuthedScoresRouteImport } from './routes/admin/_authed/scores'
import { Route as AdminAuthedReservesRouteImport } from './routes/admin/_authed/reserves'
import { Route as AdminAuthedPlayersRouteImport } from './routes/admin/_authed/players'
import { Route as AdminAuthedPlayerDatabaseRouteImport } from './routes/admin/_authed/player-database'
import { Route as AdminAuthedDashboardRouteImport } from './routes/admin/_authed/dashboard'
import { Route as AdminAuthedTournamentCreateRouteImport } from './routes/admin/_authed/tournament/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedRoute = AdminAuthedRouteImport.update({
  id: '/admin/_authed',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedSettingsRoute = AdminAuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedScoresRoute = AdminAuthedScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedReservesRoute = AdminAuthedReservesRouteImport.update({
  id: '/reserves',
  path: '/reserves',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedPlayersRoute = AdminAuthedPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedPlayerDatabaseRoute =
  AdminAuthedPlayerDatabaseRouteImport.update({
    id: '/player-database',
    path: '/player-database',
    getParentRoute: () => AdminAuthedRoute,
  } as any)
const AdminAuthedDashboardRoute = AdminAuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedTournamentCreateRoute =
  AdminAuthedTournamentCreateRouteImport.update({
    id: '/tournament/create',
    path: '/tournament/create',
    getParentRoute: () => AdminAuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthedRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard': typeof AdminAuthedDashboardRoute
  '/admin/player-database': typeof AdminAuthedPlayerDatabaseRoute
  '/admin/players': typeof AdminAuthedPlayersRoute
  '/admin/reserves': typeof AdminAuthedReservesRoute
  '/admin/scores': typeof AdminAuthedScoresRoute
  '/admin/settings': typeof AdminAuthedSettingsRoute
  '/admin/tournament/create': typeof AdminAuthedTournamentCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/dashboard': typeof AdminAuthedDashboardRoute
  '/admin/player-database': typeof AdminAuthedPlayerDatabaseRoute
  '/admin/players': typeof AdminAuthedPlayersRoute
  '/admin/reserves': typeof AdminAuthedReservesRoute
  '/admin/scores': typeof AdminAuthedScoresRoute
  '/admin/settings': typeof AdminAuthedSettingsRoute
  '/admin/tournament/create': typeof AdminAuthedTournamentCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_authed': typeof AdminAuthedRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/_authed/dashboard': typeof AdminAuthedDashboardRoute
  '/admin/_authed/player-database': typeof AdminAuthedPlayerDatabaseRoute
  '/admin/_authed/players': typeof AdminAuthedPlayersRoute
  '/admin/_authed/reserves': typeof AdminAuthedReservesRoute
  '/admin/_authed/scores': typeof AdminAuthedScoresRoute
  '/admin/_authed/settings': typeof AdminAuthedSettingsRoute
  '/admin/_authed/tournament/create': typeof AdminAuthedTournamentCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/'
    | '/admin/dashboard'
    | '/admin/player-database'
    | '/admin/players'
    | '/admin/reserves'
    | '/admin/scores'
    | '/admin/settings'
    | '/admin/tournament/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/player-database'
    | '/admin/players'
    | '/admin/reserves'
    | '/admin/scores'
    | '/admin/settings'
    | '/admin/tournament/create'
  id:
    | '__root__'
    | '/'
    | '/admin/_authed'
    | '/admin/'
    | '/admin/_authed/dashboard'
    | '/admin/_authed/player-database'
    | '/admin/_authed/players'
    | '/admin/_authed/reserves'
    | '/admin/_authed/scores'
    | '/admin/_authed/settings'
    | '/admin/_authed/tournament/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuthedRoute: typeof AdminAuthedRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed/settings': {
      id: '/admin/_authed/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAuthedSettingsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/scores': {
      id: '/admin/_authed/scores'
      path: '/scores'
      fullPath: '/admin/scores'
      preLoaderRoute: typeof AdminAuthedScoresRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/reserves': {
      id: '/admin/_authed/reserves'
      path: '/reserves'
      fullPath: '/admin/reserves'
      preLoaderRoute: typeof AdminAuthedReservesRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/players': {
      id: '/admin/_authed/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminAuthedPlayersRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/player-database': {
      id: '/admin/_authed/player-database'
      path: '/player-database'
      fullPath: '/admin/player-database'
      preLoaderRoute: typeof AdminAuthedPlayerDatabaseRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/dashboard': {
      id: '/admin/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAuthedDashboardRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/tournament/create': {
      id: '/admin/_authed/tournament/create'
      path: '/tournament/create'
      fullPath: '/admin/tournament/create'
      preLoaderRoute: typeof AdminAuthedTournamentCreateRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
  }
}

interface AdminAuthedRouteChildren {
  AdminAuthedDashboardRoute: typeof AdminAuthedDashboardRoute
  AdminAuthedPlayerDatabaseRoute: typeof AdminAuthedPlayerDatabaseRoute
  AdminAuthedPlayersRoute: typeof AdminAuthedPlayersRoute
  AdminAuthedReservesRoute: typeof AdminAuthedReservesRoute
  AdminAuthedScoresRoute: typeof AdminAuthedScoresRoute
  AdminAuthedSettingsRoute: typeof AdminAuthedSettingsRoute
  AdminAuthedTournamentCreateRoute: typeof AdminAuthedTournamentCreateRoute
}

const AdminAuthedRouteChildren: AdminAuthedRouteChildren = {
  AdminAuthedDashboardRoute: AdminAuthedDashboardRoute,
  AdminAuthedPlayerDatabaseRoute: AdminAuthedPlayerDatabaseRoute,
  AdminAuthedPlayersRoute: AdminAuthedPlayersRoute,
  AdminAuthedReservesRoute: AdminAuthedReservesRoute,
  AdminAuthedScoresRoute: AdminAuthedScoresRoute,
  AdminAuthedSettingsRoute: AdminAuthedSettingsRoute,
  AdminAuthedTournamentCreateRoute: AdminAuthedTournamentCreateRoute,
}

const AdminAuthedRouteWithChildren = AdminAuthedRoute._addFileChildren(
  AdminAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuthedRoute: AdminAuthedRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
